note: 'Default training for Titan RTX'
seed: 1

module_params:
  lr: 1e-5
  weight_decay: 0.
  gradient_checkpointing: true

trainer_params:
  epochs: 25
  gpus: -1
  weights_save_path: /mnt/ssdstuff/akirasosa/experiments/  # Save weight on SSD
  amp_level: 'O2'
  accumulate_grad_batches: 2

data_params:
  batch_size: 6
