note: 'Default training for Titan RTX'
seed: 1

module_params:
  lr: 1e-5
  weight_decay: 0.

trainer_params:
  epochs: 25
  gpus: -1
  amp_level: 'O2'
  accumulate_grad_batches: 2

data_params:
  batch_size: 6
