note: 'For V100 on GCP'
seed: 1

module_params:
  lr: 1e-5
  weight_decay: 0.
  gradient_checkpointing: true

trainer_params:
  epochs: 25
  gpus: -1
#  amp_level: 'O2'
#  accumulate_grad_batches: 3

data_params:
  batch_size: 12
